### ISSUE TITLE
Filters not visible

### ISSUE THREAD

**Issue by onsite12** [magesuite/theme-creativeshop#71]
Hi, 

The filters are not visible. 
Only standard filter price is visible. 

Attribute is enabled and working on clean magento install (migrated attribute from there) 
Running magento 2.4.1 and php 7.4 
Any suggestions?

**Comment by ggm-dev** [comment]
Check settings for the category under Display Settings > Layered Nav filters - it may be that the filters are not displaying because they don't meet the threshold for the Facet coverage rate - Set them to Display mode always displayed and that may help. 

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/66025527/115020904-de72cc80-9e80-11eb-8f7a-ea8bd0b35a4b.png">

**Comment by onsite12** [comment]
This indeed solved the issue. Thank you!
