### ISSUE TITLE
Expected Behavior if Guest Checkout is disabled

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/theme-creativeshop#93]
I just encountered an issue when trying to disable Guest Checkout under 

Stores > Configuration > Sales > Checkout > Checkout Options > Allow Guest Checkout = No

With theme set to theme-creativeshop, when I click on Proceed to Checkout in either offcanvas minicart or in shopping cart, nothing happens.  There are no error message in console.  Just nothing.  

I tried installing creativestyle/magesuite-login-or-guest-checkout-step to test behavior.  It is a slight improvement in that there is an error message that guest checkout is not allowed. .  

Default Luma behavior in 2.4.2p1 is for login/create account input to fly in upon clicking proceed to checkout when not logged and Allow Guest Checkout = No.  

Anyone have any ideas?

**Comment by ggm-dev** [comment]
I just performed a clean install of m2.4.2p2 w/sample data and install clean Magesuite v9.0.  I disabled guest checkout:

Stores > Configuration > Sales > Checkout > Checkout Options > Allow Guest Checkout = No

And had same behavior as above - can anyone out there confirm that they they are able to proceed to checkout with guest checkout disabled?  

Any help is much appreciated.

**Comment by ggm-dev** [comment]
Hi @diwipl and @creativestyle- We're struggling with this issue and I am unable to resolve - is it possible to hire you directly to look into it?  

Thanks!
David

**Comment by ggm-dev** [comment]
Just in case anyone else has the same issue, I'll provide a bit more info.  I was able to disable the Guest Checkout on the sample data clean install mentioned above by changing the setting at store scope only.  When I made change at default scope and let website inherit default and store inherit website, nothing happened.  Stranger still, is that I was able to make it work one time - and then the behavior reverted and clicking on proceed to checkout did nothing.  

We wrote a plugin to redirect to customer login if customer not logged in - we have to leave Guest checkout enabled, so certainly a hack, but it will get us through.  PM me if you need a similar solution.  I would love to discover that's it's a config setting that I've missed. . .

**Comment by msiewierska** [comment]
@ggm-dev 
Hi :)
In vendor/creativestyle/theme-creativeshop/src/Magento_Customer/layout/default.xml file we set

`<referenceBlock name="authentication-popup" display="false" />
` 
because we always use guest checkout and we do not authentication popup.

If checkout should be allowed only for logged in users please change display to true in your child theme;

`<referenceBlock name="authentication-popup" display="true" />`

It is the default Luma solution:
<img width="1086" alt="Zrzut ekranu 2021-10-12 o 14 14 21" src="https://user-images.githubusercontent.com/73164807/136954112-4efc1f56-6b1a-4b46-8efe-3cc3523901f2.png">

Please style authentication popup in your child project.

**Comment by ggm-dev** [comment]
Thank you so much.  I knew we were missing something:-(.
